-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}

-- | Contains all supported security schemes defined in the specification
module OpenAIGen.SecuritySchemes where

import qualified Data.Text as Data.Text.Internal
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Show
import qualified Network.HTTP.Client as Network.HTTP.Client.Request
import qualified Network.HTTP.Simple
import qualified OpenAIGen.Common

-- | Use this security scheme to use bearer authentication for a request. Should be used in a 'OpenAIGen.Common.Configuration'.
-- 
-- 
-- 
-- @
-- 'OpenAIGen.Configuration.defaultConfiguration'
--   { configSecurityScheme = 'bearerAuthenticationSecurityScheme' "token"
--   }
-- @
bearerAuthenticationSecurityScheme :: Data.Text.Internal.Text ->
                                      OpenAIGen.Common.SecurityScheme
bearerAuthenticationSecurityScheme = \token_0 -> Network.HTTP.Simple.addRequestHeader "Authorization" GHC.Base.$ (OpenAIGen.Common.textToByte GHC.Base.$ ("Bearer " GHC.Base.<> token_0))
