module OpenAIGen.Types.ChatCompletionRequestMessageContentPartText where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified OpenAIGen.Common
data ChatCompletionRequestMessageContentPartText
instance Show ChatCompletionRequestMessageContentPartText
instance Eq ChatCompletionRequestMessageContentPartText
instance FromJSON ChatCompletionRequestMessageContentPartText
instance ToJSON ChatCompletionRequestMessageContentPartText
