module OpenAIGen.Types.CreateTranscriptionResponse where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified OpenAIGen.Common
data CreateTranscriptionResponse
instance Show CreateTranscriptionResponse
instance Eq CreateTranscriptionResponse
instance FromJSON CreateTranscriptionResponse
instance ToJSON CreateTranscriptionResponse
