module OpenAIGen.Types.CreateAssistantFileRequest where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified OpenAIGen.Common
data CreateAssistantFileRequest
instance Show CreateAssistantFileRequest
instance Eq CreateAssistantFileRequest
instance FromJSON CreateAssistantFileRequest
instance ToJSON CreateAssistantFileRequest
