module OpenAIGen.Types.ListFineTuningJobEventsResponse where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified OpenAIGen.Common
data ListFineTuningJobEventsResponse
instance Show ListFineTuningJobEventsResponse
instance Eq ListFineTuningJobEventsResponse
instance FromJSON ListFineTuningJobEventsResponse
instance ToJSON ListFineTuningJobEventsResponse
