module OpenAIGen.Types.ListMessageFilesResponse where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified OpenAIGen.Common
data ListMessageFilesResponse
instance Show ListMessageFilesResponse
instance Eq ListMessageFilesResponse
instance FromJSON ListMessageFilesResponse
instance ToJSON ListMessageFilesResponse
