module OpenAIGen.Types.RunCompletionUsage where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified OpenAIGen.Common
data RunCompletionUsageNonNullable
instance Show RunCompletionUsageNonNullable
instance Eq RunCompletionUsageNonNullable
instance FromJSON RunCompletionUsageNonNullable
instance ToJSON RunCompletionUsageNonNullable
type RunCompletionUsage = OpenAIGen.Common.Nullable RunCompletionUsageNonNullable
