module OpenAIGen.Types.RunStepDetailsToolCallsCodeOutputLogsObject where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified OpenAIGen.Common
data RunStepDetailsToolCallsCodeOutputLogsObject
instance Show RunStepDetailsToolCallsCodeOutputLogsObject
instance Eq RunStepDetailsToolCallsCodeOutputLogsObject
instance FromJSON RunStepDetailsToolCallsCodeOutputLogsObject
instance ToJSON RunStepDetailsToolCallsCodeOutputLogsObject
